name: llama-server



x-qwen: &qwen3.8-27b
    build:
      context: .
      args:
        HF_SLUG: unsloth/Qwen3.8-27B-GGUF:Q4_K_M
        HF_TOKEN: ${HF_TOKEN:-}
    ports:
      - "${IP:-127.0.0.1}:8033:8033"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
services:
  qwen3.8-27b-8033:
    <<: *qwen3.8-27b
    ports:
      - "${IP:-127.0.0.1}:8033:8033"

  qwen3.8-27b-8034:
    <<: *qwen3.8-27b
    ports:
      - "${IP:-127.0.0.1}:8034:8033"

  qwen3.8-27b-8035:
    <<: *qwen3.8-27b
    ports:
      - "${IP:-127.0.0.1}:8035:8033"

  qwen3.8-27b-8036:
    <<: *qwen3.8-27b
    ports:
      - "${IP:-127.0.0.1}:8036:8033"

  #qwen3.8-flash-next:
  #  build:
  #    context: .
  #    args:
  #      HF_SLUG: unsloth/Qwen3.8-Flash-Next-GGUF:UD-Q4_K_XL
  #      HF_TOKEN: ${HF_TOKEN:-}
  #  container_name: llama-server-qwen3.8-flash-next
  #  environment:
  #    LLAMA_CTX_SIZE: "262144"
  #    LLAMA_CACHE_RAM: "405504"
  #    LLAMA_PORT: "8034"
  #  ports:
  #    - "${IP:-127.0.0.1}:8034:8034"
  #  restart: unless-stopped
  #  deploy:
  #    resources:
  #      reservations:
  #        devices:
  #          - driver: nvidia
  #            device_ids: ["1", "2", "3", "4", "5", "6"]
  #            capabilities: [gpu]
